#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_40 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget http://download.java.net/jdk8u40/archive/b23/binaries/jdk-8u40-ea-bin-b23-linux-x64-27_jan_2015.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.3 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget https://services.gradle.org/distributions/gradle-2.3-bin.zip
                unzip gradle-2.3-bin.zip
                rm -f gradle-2.3-bin.zip
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir gradle
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-2.3
export GRADLE_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_40
export PATH=$JAVA_HOME/bin:$GRADLE_HOME/bin:$PATH

gradle bootRepackage
