package sk.stuba.fei.team.local;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.jms.core.MessageCreator;
import org.springframework.stereotype.Component;

/**
 * Created by loucher on 29.4.2015.
 */
@Component
public class JmsProducer {

    //autogenerated by spring boot
    @SuppressWarnings("SpringJavaAutowiringInspection")
    @Autowired
    JmsTemplate jmsMessagingTemplate;

    public void sendQueueMessage(String message) {
        MessageCreator messageCreator = session -> session.createTextMessage(message);
        System.out.println("Publishing queue message:" + message);
        jmsMessagingTemplate.setPubSubNoLocal(false);
        jmsMessagingTemplate.send("test", messageCreator);
    }

    public void sendTopicMessage(String message) {
        MessageCreator messageCreator = session -> session.createTextMessage(message);
        System.out.println("Publishing  topic message:" + message);
        jmsMessagingTemplate.setPubSubNoLocal(true);
        jmsMessagingTemplate.send("test", messageCreator);
    }
}
